import Link from 'next/link';
import { pages, stats } from '@/data/site';
const cards = pages.filter(p => ['activity','service','site'].includes(p.category)).slice(0,9);
export default function Home(){return <main>
  <section className="relative overflow-hidden bg-forest px-6 py-24 text-white md:py-32">
    <div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(circle at 20% 20%, #98d2be 0, transparent 28%), radial-gradient(circle at 80% 10%, #ebbd5c 0, transparent 24%)'}} />
    <div className="container relative grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center">
      <div><p className="mb-5 inline-flex rounded-full border border-mint/40 px-4 py-2 text-sm font-bold text-mint">Ecological Industrialism · Waste Management</p><h1 className="text-4xl font-bold leading-tight md:text-6xl">פתרונות מתקדמים לפינוי וטיפול בפסולת בישראל</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#d7dbd9]">חברה תפעולית ותיקה המשלבת ניסיון, פריסה רחבה, מתקני פעילות וחשיבה סביבתית מתקדמת — עבור רשויות, תעשייה, קבלנים ולקוחות פרטיים.</p><div className="mt-8 flex flex-wrap gap-4"><Link href="/contact" className="rounded-xl bg-mint px-7 py-4 font-bold text-[#002018]">צור קשר</Link><Link href="/activity-areas" className="rounded-xl border border-white/50 px-7 py-4 font-bold">תחומי פעילות</Link></div></div>
      <div className="card bg-white/10 p-6 backdrop-blur"><div className="grid gap-4 sm:grid-cols-2">{stats.map(([n,l])=><div key={l} className="rounded-2xl border border-white/15 bg-white/10 p-5"><div className="text-3xl font-black text-mint">{n}</div><div className="mt-2 text-sm text-[#eef1ef]">{l}</div></div>)}</div></div>
    </div>
  </section>
  <section className="section"><div className="container"><div className="mb-10 flex items-end justify-between gap-6"><div><p className="text-sm font-bold text-fresh">מבנה שירותים ברור</p><h2 className="mt-2 text-3xl font-bold text-forest md:text-4xl">תחומים, אתרים ושירותים במקום אחד</h2></div><Link href="/services" className="hidden rounded-xl border border-line px-5 py-3 font-bold text-forest md:block">לכל השירותים</Link></div><div className="grid gap-5 md:grid-cols-3">{cards.map((c)=><Link key={c.slug} href={'/'+c.slug} className="card group p-6 transition hover:-translate-y-1"><div className="mb-5 h-1 w-16 rounded-full bg-gold"/><h3 className="text-xl font-bold text-forest">{c.title}</h3><p className="mt-3 leading-7 text-muted">{c.desc}</p><span className="mt-6 inline-block font-bold text-fresh">קרא עוד ←</span></Link>)}</div></div></section>
  <section className="section bg-surface-container"><div className="container grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold text-fresh">תהליך עבודה</p><h2 className="mt-2 text-3xl font-bold text-forest md:text-4xl">מקליטת פסולת ועד פתרון סביבתי מלא</h2><p className="mt-5 text-lg leading-8 text-muted">האתר בנוי כך שכל תחום פעילות מקבל עמוד תוכן מסודר, שאלות נפוצות, תגיות סמנטיות והכנה לחיבור עתידי ל־Supabase ולצ׳אט AI.</p></div><div className="grid gap-4">{['איסוף ושינוע','קליטה באתר פעילות','מיון והפרדת זרמים','מחזור / הטמנה לפי צורך'].map((x,i)=><div className="card flex items-center gap-4 p-5" key={x}><div className="grid h-10 w-10 place-items-center rounded-full bg-forest text-white font-bold">{i+1}</div><div className="font-bold text-forest">{x}</div></div>)}</div></div></section>
  <section className="px-6 py-20"><div className="container rounded-[28px] bg-forest p-10 text-center text-white md:p-16"><h2 className="text-3xl font-bold md:text-4xl">צריכים פתרון לפינוי או טיפול בפסולת?</h2><p className="mx-auto mt-4 max-w-2xl text-[#d7dbd9]">השאירו פרטים ונחזור אליכם עם מענה מתאים לפי סוג הפסולת, מיקום ואופי הפעילות.</p><Link href="/contact" className="mt-8 inline-block rounded-xl bg-mint px-8 py-4 font-bold text-[#002018]">השאירו פרטים</Link></div></section>
</main>}
